reload:
  message: "&6Plugin reloaded!"

player-join:
  motd: "&6Hey &b%player_name%&6.\nDo &a/help&6 for a list of commands\n&4[ATTENTION] &cIf you are caught using X-Ray or any other type of cheat, I will clear your inventory and obliterate your home and make you start over. Play the game fair."
  join-messages:
    - "&eWelcome %luckperms_prefix%%player_name%&e! We missed you!"
    - "&eHey what's up %luckperms_prefix%%player_name%&e."
    - "%luckperms_prefix%%player_name%&e is here!"
    - "%luckperms_prefix%%player_name%&e has entered the server!"

chat:
  format: "%luckperms_prefix%%s&r: &r%s"

tab-list:
  format: "%luckperms_prefix%%player_name%"