main: net.driedsponge.driedplugin.Main
name: DriedPlugin
version: 2.0
author: DriedSponge
api-version: 1.16
depend:
  - "PlaceholderAPI"
commands:
  log:
    description: Gives you the link to the console log
    permission: driedsponge.log
  z:
    description: Tell players you want to sleep!
    permission: driedsponge.z
  driedplugin:
    description: Plugin options
    permission: driedsponge.driedplugin
  chatpos:
    description: Share your position in chat.
    permission: driedsponge.chatpos