main: net.driedsponge.CustomServerStuff.Main
name: DriedSponge
version: 1.2
author: DriedSponge

commands:
  Broadcast:
    description: Tell a message to all players in the server.
    permission: driedsponge.broadcast
  log:
    description: Gives you the link to the console log
    permission: driedsponge.log
  z:
    description: Tell players you want to sleep!
    permission: driedsponge.z